global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'variant-a-jersey'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['variant-a-jersey:8080']

  - job_name: 'variant-c-springmvc'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['variant-c-springmvc:8080']

  - job_name: 'variant-d-springdata'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['variant-d-springdata:8080']

